-- Seed data for "fantasy_sports"."dim_rumor_form".
-- Values from the "rumor_forms" tab of the league gsheet.
-- Requires the table to already exist (see sql/ddl/rumors.sql).
--
-- IDs are inserted explicitly because other rows/arrays reference forms by value.
-- rumor_form_id is GENERATED BY DEFAULT AS IDENTITY, so explicit inserts are
-- allowed; the setval at the bottom resyncs the identity sequence.
--
-- Columns:
--   rumor_form_id    int      -- explicit, from sheet: formid
--   form_text        varchar  -- sheet: form_text
--   form_title       varchar  -- sheet: form_title
--   required_fills   text[]   -- sheet: required_fills (comma list -> array)
--   valid_sources    int[]    -- sheet: available_sources
--   valid_releases   int[]    -- not in sheet, left NULL

INSERT INTO "fantasy_sports"."dim_rumor_form"
  ("rumor_form_id", "form_text", "form_title", "required_fills", "valid_sources")
VALUES
  (1,  '"{rumor}"', 'Free Form', '{rumor}', '{}'),
  (2,  '“Discussions have been quietly circulating in the {team} front office about {rumor}.”', 'Quiet', '{rumor}', '{3,4,5,6}'),
  (3,  '“{source} say that {asset} is on the trading block.”', 'Trade Single', '{source,asset}', '{1,2,3,4,5,6,7,8,9,10}'),
  (4,  '“{source} say that {assets} and {asset} are on the market for trade.”', 'Trade Multiple', '{source,asset,assets}', '{1,2,3,4,5,6,7,8,9,10}'),
  (5,  '“{source} denies the recent trade discussions about {rumor}.”', 'Trade Denial', '{source,rumor}', '{1,2,3,4,5,6,7,8,9,10}'),
  (6,  '“Trade talks between {team1} and {team2} have escalated over {rumor}, according to {source}.”', 'Trade Talks', '{team2,rumor,source}', '{1,2,3,4,5,6,7,8,9,10}'),
  (7,  '“There is a growing feeling around the league that {asset} is on the trading block.”', 'Feeling', '{asset}', '{6,7,8,9,10,11,12,13}'),
  (8,  '“{source} say that the {team} front office has quietly been seeking offers on {rumor}.”', 'Whispers', '{source,team,rumor}', '{6,7,8,9,10,11,12,13}'),
  (9,  '“{team1} and {team2} have begun trade discussions{rumor}.”', 'Trade start', '{team2}', '{1,2,3,4,5,6,7,8,9,10}'),
  (10, '“{team1} and {team2} are trying to come to a consensus on {rumor}, according to {source}.”', 'Consensus', '{team2,rumor,source}', '{1,2,3,4,5,6,7,8,9,10}'),
  (11, '“Negotiations fell apart between {team1} and {team2}{rumor}.”', 'Fall Apart', '{team2}', '{1,2,3,4,5,6,7,8,9,10}'),
  (12, '“{team} is currently fielding offers for {rumor}.”', 'Offers', '{team,rumor}', '{6,7,8,9,10,11,12,13}'),
  (13, '“{teamset} have shown interest in {rumor}.”', 'Interest', '{teamset,rumor}', '{1,2,3,4,5,10}'),
  (14, '“There is a growing feeling around {league_name} that {asset} is on the trading block.”', 'Feeling Named', '{asset}', '{6,7,8,9,10,11,12,13}')
  ;

-- Resync the identity sequence so future inserts that omit the id continue
-- after the highest explicit id above.
SELECT setval(
  pg_get_serial_sequence('"fantasy_sports"."dim_rumor_form"', 'rumor_form_id'),
  (SELECT MAX("rumor_form_id") FROM "fantasy_sports"."dim_rumor_form")
);
