-- Seed data for "fantasy_sports"."dim_release_type".
-- Values from the "release_types" tab of the league gsheet.
-- Requires the table to already exist (see sql/ddl/rumors.sql).
--
-- IDs are inserted explicitly because they are non-sequential
-- (1,2,4,9,6,7,8,5,3,10) and are referenced by value. release_type_id is
-- GENERATED BY DEFAULT AS IDENTITY, so explicit inserts are allowed; the setval
-- at the bottom resyncs the identity sequence.
--
-- Columns:
--   release_type_id     int      -- explicit, from sheet: id
--   release_type_name   varchar  -- sheet: name
--   release_type_level  int      -- sheet: release_type_level
--   valid_forms         int[]    -- sheet: valid_forms (form ids +1 to match dim_rumor_form)

INSERT INTO "fantasy_sports"."dim_release_type"
  ("release_type_id", "release_type_name", "release_type_level", "valid_forms")
VALUES
  (1,  'none',            0, '{1,2,7}'),
  (2,  'rumor',           0, '{1,2,3,4,5,6,7,8,10,11,12,13,14}'),
  (4,  'denial',          1, '{1,5,11}'),
  (9,  'low-level leak',  1, '{1,2,3,7,8,13}'),
  (6,  'discussion',      2, '{1,2,3,4,5,6,7,8,9,10,11,12,13,14}'),
  (7,  'talks',           2, '{1,3,4,5,6,9,10,11,12,13}'),
  (8,  'high-level leak', 2, '{1,3,4,5,6,9,10,11,12}'),
  (5,  'release',         3, '{1}'),
  (3,  'statement',       4, '{1,2,3,4,5,6,9,10,11,12}'),
  (10, 'league release',  5, '{1}')
  ;

-- Resync the identity sequence so future inserts that omit the id continue
-- after the highest explicit id above.
SELECT setval(
  pg_get_serial_sequence('"fantasy_sports"."dim_release_type"', 'release_type_id'),
  (SELECT MAX("release_type_id") FROM "fantasy_sports"."dim_release_type")
);
