-- Seed data for "fantasy_sports"."dim_source_type".
-- Values from the "source_types" tab of the league gsheet.
-- Requires the table to already exist (see sql/ddl/rumors.sql).
--
-- IDs are inserted explicitly because dim_rumor_form.valid_sources references
-- them by value. source_type_id is GENERATED BY DEFAULT AS IDENTITY, so explicit
-- inserts are allowed; the setval at the bottom resyncs the identity sequence.
--
-- Columns:
--   source_type_id     int      -- explicit, from sheet
--   source_type_name   varchar  -- sheet: source_name
--   source_type_level  int      -- sheet: source_level
--   is_internal        bool     -- sheet: internal (1/0)
--   valid_forms        int[]    -- not in sheet, left NULL

INSERT INTO "fantasy_sports"."dim_source_type"
  ("source_type_id", "source_type_name", "source_type_level", "is_internal")
VALUES
  (1,  'the GM of {team}',                          4, true),
  (2,  'President of Basketball Ops, {manager}',    4, true),
  (3,  'higher ups within the {team} front office', 3, true),
  (4,  'members of the {team} front office',        2, true),
  (5,  '{team} execs',                              3, true),
  (6,  'representatives of {team}',                 2, true),
  (7,  'rival team(s)',                             1, false),
  (8,  'the front office of {team}',                2, false),
  (9,  'the GM of {team}',                          2, false),
  (10, 'the Commissioner',                          5, true),
  (11, 'the agent of {player}',                     1, false),
  (12, 'representatives of {player}',               1, false),
  (13, 'players on {team}',                         1, true),
  -- Not on the sheet; added afterwards, and load-bearing. Level 0 is the floor,
  -- so this is the one source that can carry nothing heavier than a 'none' or a
  -- 'rumor' -- and the only way to put something out unattributed. Dropping it
  -- costs the anonymous rumor entirely.
  (14, 'anonymous sources',                         0, false)
  ;

-- Resync the identity sequence so future inserts that omit the id continue
-- after the highest explicit id above.
SELECT setval(
  pg_get_serial_sequence('"fantasy_sports"."dim_source_type"', 'source_type_id'),
  (SELECT MAX("source_type_id") FROM "fantasy_sports"."dim_source_type")
);
