-- DDL for the rumor subsystem of the fantasy_sports schema.
-- Split out of schema.sql: the rumor lookup dimensions and the fact_rumor fact.
--
-- Depends on schema.sql having already created "fantasy_sports"."dim_league",
-- "dim_online_league" and "dim_manager", which fact_rumor references. Run this
-- after schema.sql.
--
--   Real-life refs : fact_rumor -> dim_league, dim_online_league, dim_manager
--   Rumor lookups  : dim_source_type, dim_rumor_form, dim_release_type

-- Drop child-first so foreign keys never block a rebuild.
DROP TABLE IF EXISTS "fantasy_sports"."fact_rumor";
DROP TABLE IF EXISTS "fantasy_sports"."dim_release_type";
DROP TABLE IF EXISTS "fantasy_sports"."dim_rumor_form";
DROP TABLE IF EXISTS "fantasy_sports"."dim_source_type";

-- ---------------------------------------------------------------------------
-- Rumor lookup dimensions
-- ---------------------------------------------------------------------------

CREATE TABLE "fantasy_sports"."dim_source_type" (
  "source_type_id" int GENERATED BY DEFAULT AS IDENTITY,
  "source_type_name" varchar,
  "source_type_level" int,
  "is_internal" bool,
  "valid_forms" int[],
  PRIMARY KEY ("source_type_id")
);

CREATE TABLE "fantasy_sports"."dim_rumor_form" (
  "rumor_form_id" int GENERATED BY DEFAULT AS IDENTITY,
  "form_text" varchar,
  "form_title" varchar,
  "required_fills" text[],
  "valid_sources" int[],
  "valid_releases" int[],
  PRIMARY KEY ("rumor_form_id")
);

CREATE TABLE "fantasy_sports"."dim_release_type" (
  "release_type_id" int GENERATED BY DEFAULT AS IDENTITY,
  "release_type_name" varchar,
  "release_type_level" int,
  "valid_forms" int[],
  PRIMARY KEY ("release_type_id")
);

-- ---------------------------------------------------------------------------
-- Real-life-grain rumor fact
-- ---------------------------------------------------------------------------

-- One row per reported rumor. The reporting manager and the season are stored
-- alongside the lookups because the source and form texts are format strings:
-- "{team}" and "{manager}" are filled from whoever reported it, in the season
-- they reported it in, and a team name changes from one season to the next. A
-- rumor that only knew its own text could never be rendered again.
--
-- league_year duplicates dim_online_league.league_year, the same way dim_team
-- carries both -- it is what "rumors this season" filters on, and the join
-- exists only to reach it.
CREATE TABLE "fantasy_sports"."fact_rumor" (
  "rumor_id" int GENERATED BY DEFAULT AS IDENTITY,
  "league_id" int,
  "online_league_id" int,
  "league_year" int,
  "manager_id" int,
  "rumor_form_id" int,
  "source_type_id" int,
  "release_type_id" int,
  -- bigint, not int: the bot stores an opaque surrogate for a Discord id, and
  -- those are 62-bit (see wojbot/core/discord_anon.py). Unused until the
  -- "{player}" source types are wired up.
  "player_discord_id" bigint,
  "rumor_text" varchar,
  "reported_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("rumor_id"),
  CONSTRAINT "FK_fact_rumor_league_id"
    FOREIGN KEY ("league_id")
      REFERENCES "fantasy_sports"."dim_league"("league_id"),
  CONSTRAINT "FK_fact_rumor_online_league_id"
    FOREIGN KEY ("online_league_id")
      REFERENCES "fantasy_sports"."dim_online_league"("online_league_id"),
  CONSTRAINT "FK_fact_rumor_manager_id"
    FOREIGN KEY ("manager_id")
      REFERENCES "fantasy_sports"."dim_manager"("manager_id"),
  CONSTRAINT "FK_fact_rumor_rumor_form_id"
    FOREIGN KEY ("rumor_form_id")
      REFERENCES "fantasy_sports"."dim_rumor_form"("rumor_form_id"),
  CONSTRAINT "FK_fact_rumor_source_type_id"
    FOREIGN KEY ("source_type_id")
      REFERENCES "fantasy_sports"."dim_source_type"("source_type_id"),
  CONSTRAINT "FK_fact_rumor_release_type_id"
    FOREIGN KEY ("release_type_id")
      REFERENCES "fantasy_sports"."dim_release_type"("release_type_id")
);

-- The read path is always "this league's rumors, this season, newest first".
CREATE INDEX "IX_fact_rumor_league_season" ON "fantasy_sports"."fact_rumor"
  ("league_id", "league_year", "reported_at" DESC);
